### Kiểm tra GET
GET http://localhost:4000/add-product/685b77cec6385923144a8336
###

POST http://localhost:4000/add-product
Content-Type: application/json

{
    "name": "Vợt cầu lông",
    "type": "Racket",
    "price": "300000",
    "countInStock": "10",
    "description":"Vợt này rất tuyệt vời",
    "brand": "VNB"
}

### Kiểm tra DELETE
DELETE http://localhost:4000/add-product/685b77cec6385923144a8336

### Kiểm tra PATCH

PATCH http://localhost:4000/add-product/685d27c78728398630183d93
Content-type: application/json

{
    "name": "New Name",
    "type": "Racket",
    "brand":"ANB",
    "price": "30000",
    "description":"...",
    "countInStock":"9"
}

### Kiểm tra GET
GET http://localhost:4000/admin/user-list